### ISSUE TITLE
soundex.phonetics("h") causes IndexError: string index out of range

### ISSUE THREAD

**Issue by sergio-weploy** [Lilykos/pyphonetics#1]
Hi!

I'm using your soundex implementation with a dictionary that contains "h" and "w".  However, soundex crashes when I use those entries in the dictionary.

Why are those letters "marked" as "D" in the translation table?

More info on the error:

```python
soundex.py", line 37, in phonetics
    if tail[0] == self.translations[first_letter]:
```

**Comment by Lilykos** [comment]
Solved (quite late I have to say) in the new version, thanks for the feedback!
